/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zcomapproach.garden.peony.email;

import com.zcomapproach.garden.peony.PeonyTopComponent;
import com.zcomapproach.garden.peony.settings.PeonyProperties;
import com.zcomapproach.garden.peony.view.PeonyFaceController;
import com.zcomapproach.garden.peony.view.controllers.SpamRulePaneController;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Singleton top component which displays spam rule for email module.
 */
@TopComponent.Description(
        preferredID = "SpamRuleTopComponent",
        iconBase = "com/zcomapproach/garden/peony/resources/images/spam.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS    //Not persistent because this windows demands login employee's UUID
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "com.zcomapproach.garden.peony.email.SpamRuleTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_SpamRuleAction",
        preferredID = "SpamRuleTopComponent"
)
@Messages({
    "CTL_SpamRuleAction=Spam Rule",
    "CTL_SpamRuleTopComponent=Spam Rule",
    "HINT_SpamRuleTopComponent=This is a Spam Rule window"
})
public final class SpamRuleTopComponent extends PeonyTopComponent {

    public SpamRuleTopComponent() {
        //initComponents();
        setName(Bundle.CTL_SpamRuleTopComponent());
        setToolTipText(Bundle.HINT_SpamRuleTopComponent());
        
        super.launchPeonyTopComponent(getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    @Override
    protected PeonyFaceController createPeonyFaceController() {
        if (getPeonyFaceController() == null){
            return new SpamRulePaneController(
                        PeonyProperties.getSingleton().getCurrentLoginEmployee().getEmployeeInfo().getEmployeeAccountUuid());
        }
        return getPeonyFaceController();
    }
}
