/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zcomapproach.garden.peony.admin;

import com.zcomapproach.garden.peony.PeonyTopComponent;
import com.zcomapproach.garden.peony.admin.controllers.PeonyAdminCenterController;
import com.zcomapproach.garden.peony.view.PeonyFaceController;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Singleton top component which displays administration center to support critical 
 * backend operations, e.g. backup file storage according to user-defined schedule.
 */
@TopComponent.Description(
        preferredID = "PeonyAdminServiceTopComponent",
        iconBase = "com/zcomapproach/garden/peony/resources/images/gear_in.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@Messages({
    "CTL_PeonyAdminServiceTopComponent=Peony Admin Service",
    "HINT_PeonyAdminServiceTopComponent=This is a PeonyAdminService window"
})
public final class PeonyAdminServiceTopComponent extends PeonyTopComponent {

    public PeonyAdminServiceTopComponent() {
        //initComponents();
        setName(Bundle.CTL_PeonyAdminServiceTopComponent());
        setToolTipText(Bundle.HINT_PeonyAdminServiceTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    @Override
    protected PeonyFaceController createPeonyFaceController() {
        if (getPeonyFaceController() == null){
            return new PeonyAdminCenterController();
        }
        return getPeonyFaceController();
    }
}
