/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zcomapproach.garden.peony.business;

import com.zcomapproach.garden.peony.PeonyTopComponent;
import com.zcomapproach.garden.peony.business.controllers.PeonyBusinessCenterServiceController;
import com.zcomapproach.garden.peony.view.PeonyFaceController;
import com.zcomapproach.garden.peony.view.events.PeonyFaceEvent;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@TopComponent.Description(
        preferredID = "PeonyBusinessCenterTopComponent",
        iconBase = "com/zcomapproach/garden/peony/resources/images/chart_line.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@Messages({
    "CTL_PeonyBusinessCenterTopComponent=PeonyBusinessCenter Window",
    "HINT_PeonyBusinessCenterTopComponent=This is a PeonyBusinessCenter window"
})
public final class PeonyBusinessCenterTopComponent extends PeonyTopComponent {

    public PeonyBusinessCenterTopComponent() {
        //initComponents();
        setName(Bundle.CTL_PeonyBusinessCenterTopComponent());
        setToolTipText(Bundle.HINT_PeonyBusinessCenterTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    @Override
    public void peonyFaceEventHappened(PeonyFaceEvent event) {
        super.peonyFaceEventHappened(event);
    }

    @Override
    protected PeonyFaceController createPeonyFaceController() {
        if (getPeonyFaceController() == null){
            PeonyFaceController aPeonyFaceController = new PeonyBusinessCenterServiceController();
            aPeonyFaceController.addPeonyFaceEventListener(this);
            return aPeonyFaceController;
        }
        return getPeonyFaceController();
    }
}
