/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zcomapproach.garden.peony.view;

import com.zcomapproach.garden.peony.PeonyTopComponent;
import com.zcomapproach.garden.peony.view.controllers.PeonyTalkerController;
import com.zcomapproach.garden.persistence.entity.G02DailyReport;
import com.zcomapproach.garden.persistence.peony.PeonyJob;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@TopComponent.Description(
        preferredID = "PeonyTalkerTopComponent",
        iconBase = "com/zcomapproach/garden/peony/resources/images/peony.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@Messages({
    "CTL_PublicBoardAction=Public Message Board",
    "CTL_PeonyTalkerTopComponent=Public Message Board",
    "HINT_PeonyTalkerTopComponent=Communicate with others..."
})
public final class PeonyTalkerTopComponent extends PeonyTopComponent {
    
    private PeonyTalkerController aPeonyTalkerController;

    public PeonyTalkerTopComponent() {
        //initComponents();
        setName(Bundle.CTL_PeonyTalkerTopComponent());
        setToolTipText(Bundle.HINT_PeonyTalkerTopComponent());
        
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
        if (aPeonyTalkerController != null){
            aPeonyTalkerController.stopTalker();
            aPeonyTalkerController.stopTodayJobPaneRefresher();
        }
    }

    @Override
    protected PeonyFaceController createPeonyFaceController() {
        if (getPeonyFaceController() == null){
            aPeonyTalkerController = new PeonyTalkerController();
            return aPeonyTalkerController;
        }
        return getPeonyFaceController();
    }

    void refreshTodayJobPaneForDailyReportUpdated(G02DailyReport updatedReport) {
        aPeonyTalkerController.refreshReportDescription(updatedReport);
    }

    void refreshTodayJobPaneForJobAssignmentUpdated(PeonyJob updatedPeonyJob) {
        aPeonyTalkerController.refreshTodayJobPaneForJobAssignmentUpdated(updatedPeonyJob);
    }
}
