/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zcomapproach.garden.peony.management;

import com.zcomapproach.garden.peony.PeonyTopComponent;
import com.zcomapproach.garden.peony.management.controllers.EmployeeDailyReportController;
import com.zcomapproach.garden.peony.settings.PeonyProperties;
import com.zcomapproach.garden.peony.view.PeonyFaceController;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Singleton top component which displays my-daily-report.
 */
@TopComponent.Description(
        preferredID = "MyDailyReportTopComponent",
        iconBase = "com/zcomapproach/garden/peony/resources/images/script-text.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", 
          id = "com.zcomapproach.garden.peony.management.MyDailyReportTopComponent")
@ActionReference(path = "Menu/Window", position = 0)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_MyDailyReportAction",
        preferredID = "MyDailyReportTopComponent"
)
@Messages({
    "CTL_MyDailyReportAction=My Daily Report",
    "CTL_MyDailyReportTopComponent=My Daily Report",
    "HINT_MyDailyReportTopComponent=This is my daily report"
})
public final class MyDailyReportTopComponent extends PeonyTopComponent {
    
    private EmployeeDailyReportController myDailyReportController;

    public MyDailyReportTopComponent() {
        initComponents();
        setName(Bundle.CTL_MyDailyReportTopComponent());
        setToolTipText(Bundle.HINT_MyDailyReportTopComponent());
        
        super.launchPeonyTopComponent(getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    @Override
    protected PeonyFaceController createPeonyFaceController() {
        if (myDailyReportController == null){
            myDailyReportController = new EmployeeDailyReportController(PeonyProperties.getSingleton().getCurrentLoginEmployee());
        }
        return myDailyReportController;
    }

    void refreshMyDailyReport() {
        if (myDailyReportController != null){
            myDailyReportController.refreshEmployeeDailyReport(PeonyProperties.getSingleton().getCurrentLoginEmployee());
        }
    }

}
