/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zcomapproach.garden.peony.customer;

import com.zcomapproach.garden.peony.PeonyTopComponent;
import com.zcomapproach.garden.peony.customer.controllers.CustomerServiceCenterController;
import com.zcomapproach.garden.peony.view.PeonyFaceController;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.zcomapproach.garden.peony.customer//PeonyCustomerService//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "PeonyCustomerServiceTopComponent",
        iconBase = "com/zcomapproach/garden/peony/resources/images/group.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "com.zcomapproach.garden.peony.customer.PeonyCustomerServiceTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PeonyCustomerServiceAction",
        preferredID = "PeonyCustomerServiceTopComponent"
)
@Messages({
    "CTL_PeonyCustomerServiceAction=PeonyCustomerService",
    "CTL_PeonyCustomerServiceTopComponent=Customer Service",
    "HINT_PeonyCustomerServiceTopComponent=This is a Peony's customer service center"
})
public final class PeonyCustomerServiceTopComponent extends PeonyTopComponent {
    
    private CustomerServiceCenterController targetCustomerServiceCenterController;

    public PeonyCustomerServiceTopComponent() {
        initComponents();
        setName(Bundle.CTL_PeonyCustomerServiceTopComponent());
        setToolTipText(Bundle.HINT_PeonyCustomerServiceTopComponent());
        //putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @Override
    protected PeonyFaceController createPeonyFaceController() {
        if (getPeonyFaceController() == null){
            targetCustomerServiceCenterController = new CustomerServiceCenterController();
            targetCustomerServiceCenterController.addPeonyFaceEventListener(this);
            return targetCustomerServiceCenterController;
        }
        return getPeonyFaceController();
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
