/*//GEN-LINE:variables
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zcomapproach.garden.peony.security;

import com.zcomapproach.garden.peony.view.PeonyFaceController;
import com.zcomapproach.garden.peony.PeonyTopComponent;
import com.zcomapproach.garden.peony.security.controllers.PeonySettingsPaneController;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Singleton top component which displays PeonyLocalSettings.
 */
@TopComponent.Description(
        preferredID = "PeonySettingsTopComponent",
        iconBase = "com/zcomapproach/garden/peony/resources/images/settings_gear.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "com.zcomapproach.garden.peony.security.PeonySettingsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PeonySettingsAction",
        preferredID = "PeonySettingsTopComponent"
)
@Messages({
    "CTL_PeonySettingsAction=Peony Settings",
    "CTL_PeonySettingsTopComponent=Peony Settings",
    "HINT_PeonySettingsTopComponent=Peony settings window"
})
public final class PeonySettingsTopComponent extends PeonyTopComponent {
    
    public PeonySettingsTopComponent() {
        initComponents();
        setName(Bundle.CTL_PeonySettingsTopComponent());
        setToolTipText(Bundle.HINT_PeonySettingsTopComponent());
        
        super.launchPeonyTopComponent(getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    // End of variables declaration                   
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    @Override
    protected PeonyFaceController createPeonyFaceController() {
        if (getPeonyFaceController() == null){
            return new PeonySettingsPaneController();
        }
        return getPeonyFaceController();
    }

}
